name: Docker Image CI

on:
  push:
    branches:
      - master
      - main
      - stable
  pull_request:
    branches:
      - master
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build the Docker image
      run: |
          
          COMMIT_HASH=$(git rev-parse HEAD)
          CURRENT_DATE=$(date +'%Y%m%d')
          CURRENT_DATE_WITH_HOUR=$(date +'%Y%m%d%H')
          IMAGE_NAME="ghcr.io/${{ github.repository }}"
          DOCKERFILE_CONTEXT="docker/Dockerfile"
          TMP_BUILD="/tmp/build"

          git clone https://github.com/iv-org/invidious.git ${TMP_BUILD}
          cd ${TMP_BUILD}
          git submodule update --init --recursive

          # Build image for master branch
          if [ ${{ github.ref }} == 'refs/heads/master' ] || [ ${{ github.ref }} == 'refs/heads/main' ]; then
            CHANNEL="latest"
          fi

          # Build image for stable branch
          if [ ${{ github.ref }} == 'refs/heads/stable' ]; then
            CHANNEL="stable"
            docker build . --file ${DOCKERFILE_CONTEXT} --tag ${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE}
            docker push ${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE}
            docker build . --file ${DOCKERFILE_CONTEXT} --tag ${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE_WITH_HOUR}
            docker push ${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE_WITH_HOUR}
          fi

          docker build . --file ${DOCKERFILE_CONTEXT} --tag ${IMAGE_NAME}:${COMMIT_HASH}
          docker push ${IMAGE_NAME}:${COMMIT_HASH}

          docker build . --file ${DOCKERFILE_CONTEXT} --tag ${IMAGE_NAME}:${CHANNEL}
          docker push ${IMAGE_NAME}:${CHANNEL}