name: Daily Update Submodules

on:
  schedule:
    - cron: '1 1 * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git commit -am "Update submodules"
          git push