name: Daily Update Submodules

on:
  schedule:
    - cron: '1 1 * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          if ! git diff-index --quiet HEAD --; then
            git config --global user.email "Buildbot@local"
            git config --global user.name "Build Bot"
            git commit -am "Update submodules: $(git submodule summary)"
            git push
          fi